### PR TITLE
Enabled syntax highlighting in README

### PR DESCRIPTION
**Pull request by 304NotModified**
Updated the readme with syntax highlighting for the code example

### CODE REVIEW

**Comment by 304NotModified** [comment]
Is the email public for the CLA?

**Comment by rpokorny** [comment]
> Is the email public for the CLA?

I'm afraid I don't understand your question

**Review by rpokorny — APPROVED** [review]

**Comment by 304NotModified** [comment]
For the CLA I have to enter an email address. Is that email adres publicly visible then ?

**Comment by DarthHater** [comment]
> For the CLA I have to enter an email address. Is that email adres publicly visible then ?

No, we do not make it publicly visible. It is collected so that if we update the CLA we have a concrete way to contact you (perhaps to resign, or to make you aware of changes), because GH ID is not the best way to contact someone after the fact :)

**Pull request merged**
