### PR TITLE
Webpack 4 support

### PR DESCRIPTION
**Pull request by seminolas**
Make plugin compatible with webpack 4

This pull request makes the following changes:

* changed fileDependencies type from Array to Set

### CODE REVIEW

**Comment by rpokorny** [comment]
When I run `npm install` on this branch, I'm getting a bunch of package-lock.json changes, even if I delete node_modules and clean my npm cache first.

**Comment by rpokorny** [comment]
I get test failures on this branch

**Comment by seminolas** [comment]
Sorry for that, obviously I made incorrect assumptions about how npm works. The test should pass now, and I re-ran npm install on top of the previous lock file - hopefully that should make it stable.

Also, this change renders the plugin incompatible with earlier versions of webpack - should that be mentioned in the readme?

**Comment by rpokorny** [comment]
> Also, this change renders the plugin incompatible with earlier versions of webpack - should that be mentioned in the readme?

Yes, if we know it'll only work with Webpack 4 we should mention that in the readme.

**Review by rpokorny — APPROVED** [review]

**Pull request merged**
