### PR TITLE
Webpack 5 Support

### LINKED ISSUE #20: Webpack 5 support - the fileDependencies always empty
image

### PR DESCRIPTION
**Pull request by rpokorny**
Add support for Webpack 5

This pull request makes the following changes:
* Switches to the simpler `compilation.fileDependencies` property rather than `module.fileDependencies` which doesn't appear to exist in webpack 5.
* Adds a dependency on webpack 5 in addition to the one for webpack 4
* Tests in both versions
* Doc update around the behavior of `includePackageJsons` in webpack 5

Note that webpack 5 includes the relevant package.json files in its `fileDependencies` list automatically, avoiding the need for us to calculate it ourselves (and removing the value of the `includePackageJsons` flag.

It relates to the following issue #s:
* Fixes #20

### CODE REVIEW

**Comment by rpokorny** [comment]
@deleonio let me know if this works for you.

**Review by Blacktiger — APPROVED** [review]

**Comment by deleonio** [comment]
I will check it soon

**Comment by deleonio** [comment]
**It works!**

There is a slight difference. Which shouldn't be relevant because it can be traced back to Webpack.

**NO DIFF** `webpack@^4` + `copy-modules-webpack-plugin@2.1.1` vs  `webpack@^4` + `copy-modules-webpack-plugin@PR22` (#22)
image

**TINY DIFF** `webpack@^4` + `copy-modules-webpack-plugin@2.1.1` vs  `webpack@^5` + `copy-modules-webpack-plugin@PR22` (#22)
image

**Comment by rpokorny** [comment]
These changes have been published as version 2.2.0 of this plugin.

**Pull request merged**
